apiVersion: v1
kind: Secret
metadata:
  namespace: heptio-ark
  name: cloud-credentials
  labels:
    component: aws
stringData:
  cloud: |
    [default]
    aws_access_key_id = 
    aws_secret_access_key = 
