---
apiVersion: ark.heptio.com/v1
kind: Config
metadata:
  namespace: heptio-ark
  name: default
persistentVolumeProvider:
  name: aws
  config:
    region: us-east-2
backupStorageProvider:
  name: aws
  bucket: aws-sandbox-poc-gaming
  config:
    region: us-east-2
